In [6]:
import pandas as pd
data = pd.read_csv('at20190929.csv', sep=',', error_bad_lines=False, index_col=False, encoding="ISO-8859-1") 



data['PIRM_REG_DATA_LT'] =pd.to_datetime(data['PIRM_REG_DATA_LT'], errors='coerce')

data3 = data['PIRM_REG_DATA_LT'] > '2016'


filtered =data[data3]

In [7]:
filtered.head()

,MARKE,KOMERCINIS_PAV,GAMINTOJO_PAV,GAMINTOJO_PAV_BAZ,TIPAS,VARIANTAS,VERSIJA,TIPO_PATVIRTINIMO_NR,UZBAIGTUMO_PAKOPA,KATEGORIJA_PILNAI,...,DAE_STATUSAS,KILMES_SALIS,APRIBOJIMAI,APRIBOJIMO_PRADZIOS_DATA,VALD_TIPAS,SAVIVALDYBE,APSKRITIS,SANDORIO_SUMA,VALIUTA,SANDORIO_DATA
27903,MAZDA,MAZDA CX-5,MAZDA MOTOR CORPORATION,NaN,GH,F91,60E,e1*2001/116*0448*23,NaN,M1------,...,T,NaN,NaN,NaN,Juridinis,VILNIAUS M. SAV.,VIL,25000.0,EUR,2015-01-04
27904,SUBARU,LEGACY,FUJI HEAVY INDUSTRIES LTD,NaN,B6,BS9,C8L,e1*2007/46*1320*00,NaN,M1------,...,T,NaN,NaN,NaN,Juridinis,VILNIAUS M. SAV.,VIL,33900.0,EUR,2015-01-04
27909,HYUNDAI,HYUNDAI SANTA FE 2.0 TD,NaN,NaN,NaN,V2,DAJ,e11*98/14*0162*05,NaN,M1-AC---,...,N,SWE,NaN,NaN,Juridinis,RADVILIÐKIO R. SAV.,ÐIA,700.0,EUR,2015-01-05
28219,MERCEDES BENZ,SPRINTER 312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N1------,...,T,DEU,NaN,NaN,Juridinis,PASVALIO R. SAV.,PAN,3500.0,EUR,2015-01-12
28482,LOHR,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O4------,...,T,FRA,NaN,NaN,Juridinis,TAURAGËS R. SAV.,TAU,NaN,EUR,2015-01-15

In [8]:


data = filtered[['MARKE', 'PIRM_REG_DATA_LT', 'PASKUTINES_REG_DATA',
                 'DEGALAI', 'KILMES_SALIS', 'SANDORIO_SUMA', 'VALIUTA', 'SANDORIO_DATA',
                'GALIA', 'DARBINIS_TURIS', 'PIRM_REG_DATA']]
data

,MARKE,PIRM_REG_DATA_LT,PASKUTINES_REG_DATA,DEGALAI,KILMES_SALIS,SANDORIO_SUMA,VALIUTA,SANDORIO_DATA,GALIA,DARBINIS_TURIS,PIRM_REG_DATA
27903,MAZDA,2016-01-04,2016-01-04,Dyzelinas,NaN,25000.0,EUR,2015-01-04,110.0,2191.0,2016-01-04
27904,SUBARU,2016-01-06,2016-01-06,Benzinas,NaN,33900.0,EUR,2015-01-04,129.0,2498.0,2016-01-06
27909,HYUNDAI,2016-01-11,2016-01-11,Dyzelinas,SWE,700.0,EUR,2015-01-05,83.0,1991.0,2002-06-27
28219,MERCEDES BENZ,2016-01-13,2016-01-13,Dyzelinas,DEU,3500.0,EUR,2015-01-12,90.0,2874.0,1997-09-29
28482,LOHR,2016-01-12,2016-01-12,--,FRA,NaN,EUR,2015-01-15,NaN,NaN,1999-10-11
28673,BOMBARDIER,2016-01-13,2016-01-13,Benzinas,NaN,11700.0,EUR,2015-01-20,14.7,976.0,2016-01-13
29227,SCHMITZ Cargobull,2016-01-07,2016-01-07,--,NaN,21500.0,EUR,2015-01-28,NaN,NaN,2016-01-07
33479,VW,2016-01-13,2016-01-13,Benzinas / Dujos,DEU,900.0,EUR,2015-04-12,55.0,1781.0,1994-05-02
36818,SCANIA,2016-01-15,2017-02-20,Dyzelinas,BEL,9000.0,EUR,2015-06-03,294.0,11705.0,1996-08-02
36989,HONDA,2016-01-04,2016-01-04,Dyzelinas,NaN,38500.0,EUR,2015-06-05,118.0,1597.0,2016-01-04
37340,MAJAVA,2016-01-12,2016-01-12,--,NaN,3200.0,EUR,2015-06-12,NaN,NaN,2016-01-12
37614,E SREMA,2016-01-07,2016-01-07,--,ROM,12584.0,EUR,2015-06-17,NaN,NaN,1999-11-04
39168,MAN,2016-01-08,2016-01-08,Dyzelinas,DEU,22000.0,EUR,2015-07-14,338.0,12816.0,2001-04-06
39323,VW,2016-01-05,2016-01-05,Dyzelinas,NaN,71245.0,EUR,2015-07-16,103.0,1968.0,2016-01-05
39324,VW,2016-01-05,2016-01-05,Dyzelinas,NaN,71245.0,EUR,2015-07-16,103.0,1968.0,2016-01-05
39503,BMW,2016-01-11,2016-01-11,Benzinas,NaN,78854.0,EUR,2015-07-20,225.0,2979.0,2016-01-11
41114,Tiki,2016-01-08,2016-01-08,--,NaN,808.0,EUR,2015-08-18,NaN,NaN,2016-01-08
41485,ROFA,2016-01-16,2016-01-16,--,POL,7260.0,EUR,2015-08-25,NaN,NaN,1996-02-06
41539,DACIA,2016-01-05,2016-01-05,Benzinas,NaN,NaN,EUR,2015-08-26,84.0,1598.0,2016-01-05
41540,DACIA,2016-01-05,2016-01-05,Benzinas,NaN,NaN,EUR,2015-08-26,84.0,1598.0,2016-01-05
41610,BMW,2016-01-14,2016-01-14,Benzinas,NaN,42814.8,EUR,2015-08-26,135.0,1997.0,2016-01-14
42433,VOLKSWAGEN,2016-01-14,2016-01-14,Dyzelinas,FIN,1115.5,EUR,2015-09-08,80.0,2460.0,2000-02-04
42701,BMW,2016-01-19,2016-01-19,Benzinas,NaN,21700.0,EUR,2015-09-11,110.0,1499.0,2016-01-19
42715,VOLKSWAGEN. VW,2016-01-04,2016-01-04,Dyzelinas,NaN,67870.0,EUR,2015-09-11,193.0,2967.0,2016-01-04
42777,VOLKSWAGEN. VW,2016-01-19,2016-01-19,Dyzelinas,NaN,20050.0,EUR,2015-09-14,81.0,1968.0,2016-01-19
43133,MERCEDES BENZ,2016-01-07,2016-01-07,Dyzelinas,FRA,18500.0,EUR,2015-09-17,125.0,2143.0,2013-06-28
43334,FORD,2016-01-05,2016-01-05,Dyzelinas,NaN,30300.0,EUR,2015-09-21,92.0,2198.0,2016-01-05
43335,FORD,2016-01-05,2016-01-05,Dyzelinas,NaN,30300.0,EUR,2015-09-21,92.0,2198.0,2016-01-05
43336,FORD,2016-01-05,2016-01-05,Dyzelinas,NaN,30300.0,EUR,2015-09-21,92.0,2198.0,2016-01-05
43774,PEUGEOT,2016-01-15,2016-02-02,Dyzelinas,FRA,6000.0,EUR,2015-09-25,100.0,1997.0,2008-03-07
...,...,...,...,...,...,...,...,...,...,...,...
1872737,AUDI,2019-09-06,2019-09-06,Benzinas,USA,1330.0,USD,2019-05-23,260.0,2995.0,NaN
1872738,JEEP,2019-09-04,2019-09-04,Benzinas,USA,1120.0,USD,2019-05-27,NaN,NaN,NaN
1872739,BMW,2019-09-04,2019-09-04,Dyzelinas,USA,1200.0,USD,2019-05-31,NaN,NaN,NaN
1872740,HONDA,2019-06-06,2019-06-06,Benzinas,GBR,2000.0,USD,2019-05-31,48.0,680.0,2007-04-16
1872741,TOYOTA,2019-09-18,2019-09-18,Benzinas / Elektra,GBR,450.0,USD,2019-06-02,NaN,NaN,NaN
1872742,MAZDA,2019-09-27,2019-09-27,Benzinas,USA,1200.0,USD,2019-06-10,NaN,NaN,NaN
1872743,CHRYSLER,2019-06-11,2019-06-11,Benzinas,USA,4588.0,USD,2019-06-10,211.0,3604.0,NaN
1872744,AUDI,2019-09-12,2019-09-12,Benzinas,CAN,1300.0,USD,2019-06-13,NaN,NaN,NaN
1872745,VOLKSWAGEN,2019-09-11,2019-09-11,Benzinas,USA,1080.0,USD,2019-06-14,NaN,NaN,NaN
1872746,JEEP,2019-09-25,2019-09-25,Benzinas,USA,1150.0,USD,2019-06-16,93.0,NaN,NaN
1872747,BMW,2019-09-13,2019-09-13,Benzinas,USA,1140.0,USD,2019-06-21,NaN,NaN,NaN
1872748,AUDI,2019-09-12,2019-09-12,Benzinas,USA,610.0,USD,2019-06-26,NaN,NaN,NaN
1872749,TOYOTA,2019-09-20,2019-09-20,Benzinas / Elektra,USA,3653.0,USD,2019-06-26,98.0,1798.0,NaN
1872750,AUDI,2019-09-25,2019-09-25,Benzinas,CAN,1300.0,USD,2019-06-27,NaN,NaN,NaN
1872751,VOLVO,2019-09-17,2019-09-17,Benzinas,USA,800.0,USD,2019-06-28,NaN,NaN,NaN
1872752,MERCEDES-BENZ,2019-08-20,2019-08-20,Benzinas,USA,6023.0,USD,2019-07-03,225.0,4966.0,NaN
1872753,VW,2019-07-12,2019-07-12,Benzinas,USA,3860.0,USD,2019-07-03,125.0,1798.0,NaN
1872754,MAZDA,2019-09-19,2019-09-19,Benzinas,USA,1180.0,USD,2019-07-06,NaN,NaN,NaN
1872755,CHRYSLER,2019-09-14,2019-09-14,Benzinas,USA,900.0,USD,2019-07-08,NaN,NaN,NaN
1872756,HARLEY-DAVIDSON,2019-07-30,2019-07-30,Benzinas,USA,150.0,USD,2019-07-08,58.0,1688.0,NaN
1872757,DUCATI,2019-08-22,2019-08-22,Benzinas,USA,3000.0,USD,2019-07-10,109.0,1198.0,NaN
1872758,BUICK,2019-09-26,2019-09-26,Benzinas,USA,800.0,USD,2019-07-12,NaN,NaN,NaN
1872759,CHRYSLER,2019-09-27,2019-09-27,Benzinas,USA,1200.0,USD,2019-07-15,211.0,3605.0,NaN
1872760,MERCEDES-BENZ,2019-09-19,2019-09-19,Benzinas,USA,850.0,USD,2019-07-19,NaN,NaN,NaN
1872761,TESLA,2019-09-06,2019-09-06,Elektra,USA,3240.0,USD,2019-07-22,NaN,NaN,NaN
1872762,AUDI,2019-09-20,2019-09-20,Benzinas,USA,13160.0,USD,2019-07-23,NaN,NaN,NaN
1872763,VOLVO,2019-09-19,2019-09-19,Benzinas,USA,580.0,USD,2019-07-25,NaN,NaN,NaN
1872764,MAZDA,2019-09-27,2019-09-27,Benzinas,USA,1140.0,USD,2019-07-30,NaN,NaN,NaN
1872765,BMW,2019-09-17,2019-09-17,Benzinas,USA,1050.0,USD,2019-08-04,NaN,NaN,NaN
1872766,MERCEDES-BENZ,2019-09-28,2019-09-28,Dyzelinas,USA,1050.0,USD,2019-08-14,NaN,NaN,2019-09-28

In [9]:
filteredBIn = data .groupby([data ['PIRM_REG_DATA_LT'].dt.year,'MARKE'])['MARKE'].count().to_frame('Count').reset_index()
data3 = filteredBIn['Count'] > 2000
filtered4 =filteredBIn[data3]
markes = set()
for x in filtered4['MARKE']:
    markes.add(x)
markes

{'AUDI',
 'BMW',
 'CITROEN',
 'DAF',
 'FORD',
 'HONDA',
 'HYUNDAI',
 'KIA',
 'KRONE',
 'MERCEDES BENZ',
 'MERCEDES-BENZ',
 'NISSAN',
 'Nuasmeninta',
 'OPEL',
 'PEUGEOT',
 'RENAULT',
 'SCHMITZ Cargobull',
 'SEAT',
 'SKODA',
 'SUBARU',
 'TOYOTA',
 'VOLKSWAGEN',
 'VOLKSWAGEN-VW',
 'VOLKSWAGEN. VW',
 'VOLVO',
 'VW'}

Buvo pastebėta, kad tarp populiariausių nėra *VOLKSWAGEN* ir *MERCEDES BENZ* automobilių, nors regitros puslapyje jie yra tarp populiariausių. Nustatyta, kad ne visos automobilių markės parašytos teisingai (identiški pavadinimai), todėl buvo atliktas duomenų valymas (pavadinima pakeisti taip, kad būtų vienodi tai automobilių markei)

In [10]:
data['MARKE'].replace(to_replace='MERCEDES-BENZ', value='MERCEDES BENZ', inplace= True)
data['MARKE'].replace(to_replace='VOLKSWAGEN-VW', value='VOLKSWAGEN', inplace= True)
data['MARKE'].replace(to_replace='VW', value='VOLKSWAGEN', inplace= True)
data['MARKE'].replace(to_replace='VOLKSWAGEN. VW', value='VOLKSWAGEN', inplace= True)

C:\Algirdo\Magistras\MasininisMokymasis\WPy64-3740\python-3.7.4.amd64\lib\site-packages\pandas\core\generic.py:6586: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [11]:

filteredBIn = data .groupby([data ['PIRM_REG_DATA_LT'].dt.year,'MARKE'])['MARKE'].count().to_frame('Count').reset_index()
data3 = filteredBIn['Count'] > 2000
filtered4 =filteredBIn[data3]
markes = set()
for x in filtered4['MARKE']:
    markes.add(x)
markes

{'AUDI',
 'BMW',
 'CITROEN',
 'DAF',
 'FORD',
 'HONDA',
 'HYUNDAI',
 'KIA',
 'KRONE',
 'MERCEDES BENZ',
 'NISSAN',
 'Nuasmeninta',
 'OPEL',
 'PEUGEOT',
 'RENAULT',
 'SCHMITZ Cargobull',
 'SEAT',
 'SKODA',
 'SUBARU',
 'TOYOTA',
 'VOLKSWAGEN',
 'VOLVO'}

In [12]:
data.to_csv ('exported_car_model_data.csv', index = None, header=True,  sep=',', )